data_provenances:
  - gisaid
variant_classifications:
  - pango_lineages
geo_resolutions:
  - global
analysis_periods:
  - xbb15

# Params for the prepare data scripts
# Define params for each data_provenance / variant_classification / geo_resolution combination
# Include `max_date` if you don't want to use today as the max date
prepare_data:
  gisaid:
    pango_lineages:
      global:
        min_date: "2023-01-01"
        max_date: "2023-12-01"
        location_min_seq: 1000
        excluded_locations: "defaults/global_excluded_locations.txt"
        clade_min_seq: 1
        collapse_threshold: 350

prepare_predictors:
  current_dms:
    input_data: "results/summaries/summary.csv"
    rename_cols: {"human sera escape": "sera escape", "spike mediated entry": "cell entry"}
    phenotype_cols: ["sera escape", "ACE2 binding", "cell entry"]
    title: "XBB.1.5 full-spike DMS phenotypes"
    missing_muts: "drop"  # drop clades with missing muts,
  yeast_RBD_DM:
    input_data: "data/compare_natural_datasets/yeast_RBD_DMS.csv"
    rename_cols: {}
    phenotype_cols: ["escape", "ACE2 affinity", "RBD expression"]
    title: "yeast RBD DMS phenotypes"
    missing_muts: "zero"  # set missing (non-RBD) mutations to zero
  muts_from_Wuhan-Hu-1:
    input_data: "data/compare_natural_datasets/incremental_Hamming_distance_from_Wuhan-Hu-1.csv"
    rename_cols: {"incremental Hamming distance": "distance"}
    phenotype_cols: ["distance"]
    title: "relative distance from Wuhan-Hu-1"
    missing_muts": "drop"  # drop clades with missing muts
  EVEscape:
    input_data: "data/compare_natural_datasets/EVEscape_XBB_single_mutation_predictions.csv"
    rename_cols: {}
    phenotype_cols: ["EVEscape"]
    title: "EVEscape"
    missing_muts: "drop"  # drop clades with missing muts
  EVEscape_components:
    input_data: "data/compare_natural_datasets/EVEscape_XBB_single_mutation_predictions.csv"
    rename_cols: {"fitness_evol_indices": "EVE fitness", "dissimilarity_charge_hydrophobicity": "aa dissimilarity", "accessibility_wcn": "accessibility"}
    phenotype_cols: ["EVE fitness", "aa dissimilarity", "accessibility"]
    title: "EVEscape components"
    missing_muts: "drop"  # drop clades with missing muts

# In case we want to run models for various different pandemic periods
analysis_period:
  # ba2:
  #   included_days: 150
  #   date_max: "2022-"
  #   pivot: "BA.2"
  xbb15:
    num_days_context: 90
    obs_date_min: "2023-01-01"
    obs_date_max: "2023-12-01"
    obs_date_interval: "2W"
    pivot: "XBB.1.5"
