data_provenances:
  - gisaid
variant_classifications:
  - pango_lineages
geo_resolutions:
  - global
analysis_periods:
  - xbb15

# Params for the prepare data scripts
# Define params for each data_provenance / variant_classification / geo_resolution combination
# Include `max_date` if you don't want to use today as the max date
prepare_data:
  gisaid:
    pango_lineages:
      global:
        location_min_seq: 1000
        excluded_locations: "defaults/global_excluded_locations.txt"
        clade_min_seq: 1
        collapse_threshold: 200

# In case we want to run models for various different pandemic periods
analysis_period:
  # ba2:
  #   included_days: 150
  #   date_max: "2022-"
  #   pivot: "BA.2"
  ba2:
    min_date: "2021-11-01"
    max_date: "2022-11-01"
    pivot: "BA.2"
  xbb15:
    min_date: "2023-01-01"
    max_date: "2023-12-01"
    pivot: "XBB.1.5"
    force_include: "defaults/xbb15/force_include_lineages.txt"
    predictor_names:
      - 'spike pseudovirus DMS Non-RBD human sera escape relative to XBB.1.5'
      - 'spike pseudovirus DMS Non-RBD ACE2 binding relative to XBB.1.5'
  xbb15_windowed:
    windowed: true
    obs_date_min: "2023-01-01"
    obs_date_max: "2023-12-01"
    interval: "2M"
    pivot: "XBB.1.5"
    num_days_context: 90
  jn1:
    min_date: "2024-01-01"
    max_date: "2024-10-01"
    pivot: "JN.1"
